/* The following code was generated by JFlex 1.6.1 */

import java_cup.runtime.*;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.1
 * from the specification file <tt>src/Lexer.lex</tt>
 */
class Lexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\3\1\2\1\6\1\7\1\1\22\0\1\3\1\55\1\17"+
    "\1\5\2\16\1\56\1\15\1\62\1\63\1\53\1\52\1\71\1\47"+
    "\1\14\1\4\1\12\11\13\1\51\1\70\1\60\1\61\1\50\2\0"+
    "\5\10\1\46\15\10\1\45\6\10\1\64\1\20\1\65\1\54\1\11"+
    "\1\0\1\25\1\36\1\32\1\31\1\34\1\26\1\10\1\40\1\21"+
    "\1\10\1\43\1\27\1\44\1\22\1\30\1\37\1\35\1\24\1\33"+
    "\1\23\1\41\1\10\1\42\3\10\1\66\1\57\1\67\7\0\1\6"+
    "\u1fa2\0\1\6\1\6\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\udfe6\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\2\2\1\3\1\2\1\4\2\5\1\6"+
    "\2\1\1\7\15\4\1\10\1\11\1\12\1\13\1\14"+
    "\1\15\1\16\1\17\1\20\1\21\1\22\1\23\1\1"+
    "\1\24\1\25\1\26\1\27\1\30\1\31\1\32\1\33"+
    "\5\0\1\34\1\0\1\35\1\36\6\4\1\37\4\4"+
    "\1\40\1\4\1\41\7\4\1\42\1\43\1\44\1\45"+
    "\1\46\1\47\1\50\1\51\1\52\1\0\2\53\2\54"+
    "\1\55\1\56\1\57\3\4\1\60\10\4\1\61\1\62"+
    "\7\4\1\63\1\4\1\64\1\4\1\65\3\4\1\66"+
    "\1\4\1\67\1\70\1\71\1\4\1\72\2\4\1\73"+
    "\2\4\1\74\1\75\2\4\1\76\1\77\1\100\1\101"+
    "\1\102\1\103\2\4\1\104";

  private static int [] zzUnpackAction() {
    int [] result = new int[148];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\72\0\164\0\72\0\256\0\350\0\u0122\0\u015c"+
    "\0\u0196\0\72\0\u01d0\0\u020a\0\72\0\u0244\0\u027e\0\u02b8"+
    "\0\u02f2\0\u032c\0\u0366\0\u03a0\0\u03da\0\u0414\0\u044e\0\u0488"+
    "\0\u04c2\0\u04fc\0\u0122\0\u0122\0\u0536\0\u0570\0\u05aa\0\72"+
    "\0\72\0\72\0\u05e4\0\u061e\0\u0658\0\u0692\0\u06cc\0\72"+
    "\0\72\0\72\0\72\0\72\0\72\0\72\0\72\0\u0706"+
    "\0\u0740\0\u077a\0\u07b4\0\u020a\0\72\0\u07ee\0\u0828\0\u0122"+
    "\0\u0862\0\u089c\0\u08d6\0\u0910\0\u094a\0\u0984\0\u0122\0\u09be"+
    "\0\u09f8\0\u0a32\0\u0a6c\0\u0122\0\u0aa6\0\u0122\0\u0ae0\0\u0b1a"+
    "\0\u0b54\0\u0b8e\0\u0bc8\0\u0c02\0\u0c3c\0\72\0\72\0\72"+
    "\0\72\0\72\0\72\0\72\0\72\0\72\0\u0c76\0\72"+
    "\0\u0cb0\0\72\0\u0cea\0\72\0\u0122\0\u0122\0\u0d24\0\u0d5e"+
    "\0\u0d98\0\u0122\0\u0dd2\0\u0e0c\0\u0e46\0\u0e80\0\u0eba\0\u0ef4"+
    "\0\u0f2e\0\u0f68\0\u0122\0\u0122\0\u0fa2\0\u0fdc\0\u1016\0\u1050"+
    "\0\u108a\0\u10c4\0\u10fe\0\u0122\0\u1138\0\u0122\0\u1172\0\u0122"+
    "\0\u11ac\0\u11e6\0\u1220\0\u0122\0\u125a\0\u0122\0\u0122\0\u0122"+
    "\0\u1294\0\u0122\0\u12ce\0\u1308\0\u0122\0\u1342\0\u137c\0\u0122"+
    "\0\u0122\0\u13b6\0\u13f0\0\u0122\0\u0122\0\u0122\0\u0122\0\u0122"+
    "\0\u0122\0\u142a\0\u1464\0\u0122";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[148];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\2\4\1\5\1\6\1\2\1\4\1\7"+
    "\1\2\1\10\1\11\1\12\1\13\1\2\1\14\1\15"+
    "\1\16\1\7\1\17\1\20\1\21\1\22\1\7\1\23"+
    "\1\24\1\7\1\25\1\26\1\7\1\27\1\30\2\7"+
    "\1\31\1\7\1\32\1\33\1\34\1\35\1\36\1\37"+
    "\1\40\1\41\1\42\1\43\1\44\1\45\1\46\1\47"+
    "\1\50\1\51\1\52\1\53\1\54\1\55\1\56\1\57"+
    "\74\0\1\4\74\0\1\60\64\0\1\6\2\0\3\6"+
    "\2\0\62\6\10\0\4\7\5\0\26\7\27\0\1\61"+
    "\7\0\1\62\61\0\1\61\4\0\3\11\1\62\61\0"+
    "\2\63\2\0\1\63\1\0\6\63\1\0\27\63\2\0"+
    "\2\63\1\0\2\63\3\0\2\63\5\0\1\63\17\64"+
    "\1\65\1\66\51\64\10\0\4\7\5\0\1\7\1\67"+
    "\3\7\1\70\20\7\33\0\4\7\5\0\7\7\1\71"+
    "\1\72\6\7\1\73\6\7\33\0\4\7\5\0\4\7"+
    "\1\74\6\7\1\75\12\7\33\0\4\7\5\0\6\7"+
    "\1\76\17\7\33\0\4\7\5\0\1\77\5\7\1\100"+
    "\1\101\1\102\7\7\1\103\5\7\33\0\4\7\5\0"+
    "\10\7\1\104\15\7\33\0\4\7\5\0\1\105\6\7"+
    "\1\106\16\7\33\0\4\7\5\0\13\7\1\107\12\7"+
    "\33\0\4\7\5\0\6\7\1\110\17\7\33\0\4\7"+
    "\5\0\3\7\1\111\3\7\1\112\16\7\33\0\4\7"+
    "\5\0\3\7\1\113\22\7\33\0\4\7\5\0\17\7"+
    "\1\114\6\7\33\0\4\7\5\0\4\7\1\115\21\7"+
    "\73\0\1\116\102\0\1\117\61\0\1\120\7\0\1\121"+
    "\71\0\1\122\66\0\1\123\72\0\1\124\73\0\1\125"+
    "\71\0\1\126\10\0\5\60\1\127\64\60\12\0\1\130"+
    "\1\131\70\0\1\132\1\133\73\0\1\134\54\0\1\64"+
    "\2\0\3\64\2\0\62\64\10\0\4\7\5\0\2\7"+
    "\1\135\23\7\33\0\4\7\5\0\16\7\1\136\7\7"+
    "\33\0\4\7\5\0\13\7\1\137\12\7\33\0\4\7"+
    "\5\0\3\7\1\140\7\7\1\141\12\7\33\0\4\7"+
    "\5\0\2\7\1\142\23\7\33\0\4\7\5\0\2\7"+
    "\1\143\1\7\1\144\21\7\33\0\4\7\5\0\1\145"+
    "\25\7\33\0\4\7\5\0\7\7\1\146\16\7\33\0"+
    "\4\7\5\0\3\7\1\147\22\7\33\0\4\7\5\0"+
    "\13\7\1\150\12\7\33\0\4\7\5\0\1\7\1\151"+
    "\24\7\33\0\4\7\5\0\11\7\1\152\14\7\33\0"+
    "\4\7\5\0\2\7\1\153\11\7\1\154\11\7\33\0"+
    "\4\7\5\0\1\155\11\7\1\156\13\7\33\0\4\7"+
    "\5\0\13\7\1\157\12\7\33\0\4\7\5\0\7\7"+
    "\1\160\16\7\33\0\4\7\5\0\1\161\25\7\33\0"+
    "\4\7\5\0\1\162\25\7\33\0\4\7\5\0\1\163"+
    "\25\7\23\0\4\60\1\4\1\127\64\60\11\0\3\131"+
    "\67\0\3\133\66\0\4\7\5\0\5\7\1\164\20\7"+
    "\33\0\4\7\5\0\13\7\1\165\12\7\33\0\4\7"+
    "\5\0\1\7\1\166\24\7\33\0\4\7\5\0\20\7"+
    "\1\167\5\7\33\0\4\7\5\0\10\7\1\170\15\7"+
    "\33\0\4\7\5\0\4\7\1\171\21\7\33\0\4\7"+
    "\5\0\4\7\1\172\21\7\33\0\4\7\5\0\4\7"+
    "\1\173\21\7\33\0\4\7\5\0\5\7\1\174\20\7"+
    "\33\0\4\7\5\0\11\7\1\175\14\7\33\0\4\7"+
    "\5\0\2\7\1\176\23\7\33\0\4\7\5\0\5\7"+
    "\1\177\20\7\33\0\4\7\5\0\13\7\1\200\12\7"+
    "\33\0\4\7\5\0\4\7\1\201\21\7\33\0\4\7"+
    "\5\0\6\7\1\202\17\7\33\0\4\7\5\0\1\7"+
    "\1\203\24\7\33\0\4\7\5\0\6\7\1\204\17\7"+
    "\33\0\4\7\5\0\1\7\1\205\24\7\33\0\4\7"+
    "\5\0\4\7\1\206\21\7\33\0\4\7\5\0\3\7"+
    "\1\207\22\7\33\0\4\7\5\0\12\7\1\210\13\7"+
    "\33\0\4\7\5\0\2\7\1\211\23\7\33\0\4\7"+
    "\5\0\6\7\1\212\17\7\33\0\4\7\5\0\2\7"+
    "\1\213\23\7\33\0\4\7\5\0\22\7\1\214\3\7"+
    "\33\0\4\7\5\0\2\7\1\215\23\7\33\0\4\7"+
    "\5\0\13\7\1\216\12\7\33\0\4\7\5\0\10\7"+
    "\1\217\15\7\33\0\4\7\5\0\1\7\1\220\24\7"+
    "\33\0\4\7\5\0\6\7\1\221\17\7\33\0\4\7"+
    "\5\0\1\222\25\7\33\0\4\7\5\0\7\7\1\223"+
    "\16\7\33\0\4\7\5\0\1\7\1\224\24\7\23\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[5278];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\1\1\1\11\5\1\1\11\2\1\1\11"+
    "\22\1\3\11\5\1\10\11\5\0\1\11\1\0\27\1"+
    "\11\11\1\0\1\11\1\1\1\11\1\1\1\11\70\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[148];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
  StringBuffer string = new StringBuffer();

  private Symbol symbol(int type) {
    return new Symbol(type, yyline, yycolumn, yytext());
  }
  private Symbol symbol(int type, Object value) {
    return new Symbol(type, yyline, yycolumn, value);
  }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Lexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 180) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(sym.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { throw new Error("Illegal character <"+yytext()+">");
            }
          case 69: break;
          case 2: 
            { /* ignore */
            }
          case 70: break;
          case 3: 
            { return symbol(sym.DIVISION);
            }
          case 71: break;
          case 4: 
            { return symbol(sym.IDENTIFIER);
            }
          case 72: break;
          case 5: 
            { return symbol(sym.INTEGER_LITERAL);
            }
          case 73: break;
          case 6: 
            { return symbol(sym.DOT);
            }
          case 74: break;
          case 7: 
            { return symbol(sym.SET_DIFF);
            }
          case 75: break;
          case 8: 
            { return symbol(sym.TRUE);
            }
          case 76: break;
          case 9: 
            { return symbol(sym.FALSE);
            }
          case 77: break;
          case 10: 
            { return symbol(sym.MINUS);
            }
          case 78: break;
          case 11: 
            { return symbol(sym.R_TRI_PAREN);
            }
          case 79: break;
          case 12: 
            { return symbol(sym.COLON);
            }
          case 80: break;
          case 13: 
            { return symbol(sym.PLUS);
            }
          case 81: break;
          case 14: 
            { return symbol(sym.MULTI);
            }
          case 82: break;
          case 15: 
            { return symbol(sym.POWER);
            }
          case 83: break;
          case 16: 
            { return symbol(sym.NOT);
            }
          case 84: break;
          case 17: 
            { return symbol(sym.SET_INTSECT);
            }
          case 85: break;
          case 18: 
            { return symbol(sym.PIPE);
            }
          case 86: break;
          case 19: 
            { return symbol(sym.L_TRI_PAREN);
            }
          case 87: break;
          case 20: 
            { return symbol(sym.L_SOFT_PAREN);
            }
          case 88: break;
          case 21: 
            { return symbol(sym.R_SOFT_PAREN);
            }
          case 89: break;
          case 22: 
            { return symbol(sym.L_SQ_PAREN);
            }
          case 90: break;
          case 23: 
            { return symbol(sym.R_SQ_PAREN);
            }
          case 91: break;
          case 24: 
            { return symbol(sym.L_CURL_PAREN);
            }
          case 92: break;
          case 25: 
            { return symbol(sym.R_CURL_PAREN);
            }
          case 93: break;
          case 26: 
            { return symbol(sym.SEMI);
            }
          case 94: break;
          case 27: 
            { return symbol(sym.COMMA);
            }
          case 95: break;
          case 28: 
            { return symbol(sym.STRING_LITERAL);
            }
          case 96: break;
          case 29: 
            { return symbol(sym.IN);
            }
          case 97: break;
          case 30: 
            { return symbol(sym.IF);
            }
          case 98: break;
          case 31: 
            { return symbol(sym.FI);
            }
          case 99: break;
          case 32: 
            { return symbol(sym.OD);
            }
          case 100: break;
          case 33: 
            { return symbol(sym.DO);
            }
          case 101: break;
          case 34: 
            { return symbol(sym.ARROW);
            }
          case 102: break;
          case 35: 
            { return symbol(sym.BIGGER_EQ);
            }
          case 103: break;
          case 36: 
            { return symbol(sym.SEQ_CONCAT);
            }
          case 104: break;
          case 37: 
            { return symbol(sym.ASSIGN);
            }
          case 105: break;
          case 38: 
            { return symbol(sym.NOT_EQ);
            }
          case 106: break;
          case 39: 
            { return symbol(sym.AND);
            }
          case 107: break;
          case 40: 
            { return symbol(sym.OR);
            }
          case 108: break;
          case 41: 
            { return symbol(sym.SMALLER_EQ);
            }
          case 109: break;
          case 42: 
            { return symbol(sym.EQUAL);
            }
          case 110: break;
          case 43: 
            { return symbol(sym.RATIONAL_LITERAL);
            }
          case 111: break;
          case 44: 
            { return symbol(sym.FLOAT_LITERAL);
            }
          case 112: break;
          case 45: 
            { return symbol(sym.CHAR_LITERAL);
            }
          case 113: break;
          case 46: 
            { return symbol(sym.INTEGER);
            }
          case 114: break;
          case 47: 
            { return symbol(sym.TOP);
            }
          case 115: break;
          case 48: 
            { return symbol(sym.RATIONAL);
            }
          case 116: break;
          case 49: 
            { return symbol(sym.SET);
            }
          case 117: break;
          case 50: 
            { return symbol(sym.SEQUENCE);
            }
          case 118: break;
          case 51: 
            { return symbol(sym.TYPE_DEF);
            }
          case 119: break;
          case 52: 
            { return symbol(sym.THEN);
            }
          case 120: break;
          case 53: 
            { return symbol(sym.READ);
            }
          case 121: break;
          case 54: 
            { return symbol(sym.FUN_DEF);
            }
          case 122: break;
          case 55: 
            { return symbol(sym.DICTIONARY);
            }
          case 123: break;
          case 56: 
            { return symbol(sym.ELIF);
            }
          case 124: break;
          case 57: 
            { return symbol(sym.ELSE);
            }
          case 125: break;
          case 58: 
            { return symbol(sym.BOOLEAN);
            }
          case 126: break;
          case 59: 
            { return symbol(sym.MAIN);
            }
          case 127: break;
          case 60: 
            { return symbol(sym.ALIAS);
            }
          case 128: break;
          case 61: 
            { return symbol(sym.FLOAT);
            }
          case 129: break;
          case 62: 
            { return symbol(sym.BREAK);
            }
          case 130: break;
          case 63: 
            { return symbol(sym.PRINT);
            }
          case 131: break;
          case 64: 
            { return symbol(sym.WHILE);
            }
          case 132: break;
          case 65: 
            { return symbol(sym.THREAD);
            }
          case 133: break;
          case 66: 
            { return symbol(sym.RETURN);
            }
          case 134: break;
          case 67: 
            { return symbol(sym.FORALL);
            }
          case 135: break;
          case 68: 
            { return symbol(sym.FUNCTION);
            }
          case 136: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
