
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int FORALL = 38;
  public static final int STRING_LITERAL = 67;
  public static final int FUNCTION = 29;
  public static final int BIGGER_EQ = 56;
  public static final int POWER = 51;
  public static final int TYPE_DEF = 30;
  public static final int CHAR_LITERAL = 68;
  public static final int L_CURL_PAREN = 12;
  public static final int INTEGER = 17;
  public static final int R_SQ_PAREN = 15;
  public static final int SEMI = 3;
  public static final int R_SOFT_PAREN = 13;
  public static final int MINUS = 48;
  public static final int NOT = 53;
  public static final int AND = 52;
  public static final int L_TRI_PAREN = 10;
  public static final int SEQ_CONCAT = 62;
  public static final int RATIONAL = 18;
  public static final int IN = 61;
  public static final int OR = 54;
  public static final int COMMA = 4;
  public static final int FI = 36;
  public static final int THREAD = 27;
  public static final int R_CURL_PAREN = 16;
  public static final int PLUS = 47;
  public static final int MAIN = 42;
  public static final int ASSIGN = 2;
  public static final int IF = 32;
  public static final int DOT = 6;
  public static final int EOF = 0;
  public static final int BOOLEAN = 23;
  public static final int OD = 40;
  public static final int RETURN = 31;
  public static final int EQUAL = 57;
  public static final int TRUE = 45;
  public static final int DICTIONARY = 20;
  public static final int error = 1;
  public static final int PIPE = 7;
  public static final int SET_INTSECT = 59;
  public static final int FUN_DEF = 28;
  public static final int BREAK = 41;
  public static final int RATIONAL_LITERAL = 65;
  public static final int VOID = 25;
  public static final int TOP = 24;
  public static final int ARROW = 8;
  public static final int COLON = 5;
  public static final int ELSE = 35;
  public static final int READ = 44;
  public static final int NOT_EQ = 58;
  public static final int WHILE = 37;
  public static final int FLOAT = 19;
  public static final int THEN = 33;
  public static final int MULTI = 49;
  public static final int ALIAS = 26;
  public static final int SEQUENCE = 21;
  public static final int FLOAT_LITERAL = 66;
  public static final int SET_DIFF = 60;
  public static final int FALSE = 46;
  public static final int DIVISION = 50;
  public static final int R_TRI_PAREN = 14;
  public static final int SMALLER_EQ = 55;
  public static final int L_SQ_PAREN = 11;
  public static final int ELIF = 34;
  public static final int PRINT = 43;
  public static final int DO = 39;
  public static final int SET = 22;
  public static final int L_SOFT_PAREN = 9;
  public static final int INTEGER_LITERAL = 64;
  public static final int IDENTIFIER = 63;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ASSIGN",
  "SEMI",
  "COMMA",
  "COLON",
  "DOT",
  "PIPE",
  "ARROW",
  "L_SOFT_PAREN",
  "L_TRI_PAREN",
  "L_SQ_PAREN",
  "L_CURL_PAREN",
  "R_SOFT_PAREN",
  "R_TRI_PAREN",
  "R_SQ_PAREN",
  "R_CURL_PAREN",
  "INTEGER",
  "RATIONAL",
  "FLOAT",
  "DICTIONARY",
  "SEQUENCE",
  "SET",
  "BOOLEAN",
  "TOP",
  "VOID",
  "ALIAS",
  "THREAD",
  "FUN_DEF",
  "FUNCTION",
  "TYPE_DEF",
  "RETURN",
  "IF",
  "THEN",
  "ELIF",
  "ELSE",
  "FI",
  "WHILE",
  "FORALL",
  "DO",
  "OD",
  "BREAK",
  "MAIN",
  "PRINT",
  "READ",
  "TRUE",
  "FALSE",
  "PLUS",
  "MINUS",
  "MULTI",
  "DIVISION",
  "POWER",
  "AND",
  "NOT",
  "OR",
  "SMALLER_EQ",
  "BIGGER_EQ",
  "EQUAL",
  "NOT_EQ",
  "SET_INTSECT",
  "SET_DIFF",
  "IN",
  "SEQ_CONCAT",
  "IDENTIFIER",
  "INTEGER_LITERAL",
  "RATIONAL_LITERAL",
  "FLOAT_LITERAL",
  "STRING_LITERAL",
  "CHAR_LITERAL"
  };
}

